# 워크 플로우의 이름
name: CI/CD

# 워크 플로우가 시작될 브랜치 지정
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정
    # 실행 스텝 지정
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'corretto'
          java-version: '17'
          maven-version: '3.8.4'

      # 테스트 환경
      - name: Build and Test with Maven
        run: mvn clean verify
        env:
          SPRING_DATASOURCE_URL: jdbc:h2:mem:test;MODE=MYSQL
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: password

      # 현재 시간 가져오기
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      # 배포용 패키지 경로 저장
      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp target/*.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r deploy.zip .


#name: todayExercise
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: 11
#          distribution: 'adopt'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./mvnw
#
#      - name: Build with Maven
#        run: ./mvnw clean package -DskipTests
#
#      - name: Get current time
#        id: current-time
#        run: echo "::set-output name=formattedTime::$(TZ=Asia/Seoul date +'%Y-%m-%dT%H:%M:%S')"
#
#      - name: Show Current Time
#        run: echo "CurrentTime=${{ steps.current-time.outputs.formattedTime }}"
#
#      - name: Generate deployment package
#        run: |
#          mkdir -p deploy
#          cp target/*.jar deploy/application.jar
#          cp Procfile deploy/Procfile
#          cp -r .ebextensions deploy/.ebextensions
#          cd deploy && zip -r deploy.zip .
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: todayExercise2
          environment_name: TodayExercise2-env
          version_label: aws-v5-${{ steps.current-time.outputs.formattedTime }}
          region: us-east-1
          deployment_package: deploy/deploy.zip
#
#      - name: Set up AWS CLI
#        uses: aws-actions/configure-aws-credentials@v2
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
#          aws-region: ap-northeast-2
#
#      - name: Update RDS Database
#        run: |
#          aws rds modify-db-instance \
#            --db-instance-identifier your-rds-instance-id \
#            --master-user-password your-new-rds-password
